const LAUNDERETTES = {

    areaColours: {
        h0069b4: {
            laundrette: "bare",
            name: "Clare",
            label: "Bare Laundrette",
            location: "Morecambe",
            images: "2",
            cmd: "audio",
            duration: "11m 3s",
            quote: "We operate purely on goodwill, what we have in the shops is worth nothing",
        },
        h009fe3: {
            laundrette: "brilliant",
            name: "Charlie",
            label: "It's Brilliant",
            location: "Nottingham",
            images: "",
            cmd: "audio",
            duration: "7m 23s",
            quote: "You’re the boss you never had",
        },
        hff0000: {
            laundrette: "bowwash_tim",
            cmd: "video",
            name: "Tim",
            label: "Bow Wash",
            location: "London",
            images: "",
            duration: "10m 11s",
            quote: "When you’re in people’s knickers - all boundaries disappear",
        },
        h8f99cd: {
            laundrette: "bowwash_jv",
            cmd: "video",
            name: "Juliana & Vida",
            label: "Bow Wash",
            location: "London",
            images: "",
            duration: "4m 51s",
            quote: "What happens in Bow Wash stays in Bow Wash",
        },
        h009a93: {
            laundrette: "cityroad",
            name: "Janis",
            label: "City Road Laundry",
            location: "Sheffield",
            images: "",
            cmd: "audio",
            duration: "16m 45s",
            quote: "When Mrs Green owned it, you weren’t allowed a chair, you couldn’t sit down, you were paid minimum wage. She was like Mrs Bucket… she wanted you to know that she was the boss … and you did what she said \nThere’s a lady that comes in with a teddy bear and she brings her egg sandwich into the cafe and when she comes back the teddy bear has got egg on its face, that’s her companion and she’s lovely",
        },
        hffff00: {
            laundrette: "super_merlyn",
            name: "Merlyn",
            label: "Super Laundry Company",
            location: "London",
            images: "",
            cmd: "video",
            duration: "4m 35s",
            quote: "I live in a flat, we don’t have the drying space… I’ve got three children… … I am here so often the customers think I work here",
        },
        h9185be: {
            laundrette: "super_ikey",
            name: "Ikey",
            label: "Super Laundry Company",
            location: "London",
            images: "",
            cmd: "video",
            duration: "2m 18s",
            quote: "These machines will last more than a human",
        },
        h951b81: {
            laundrette: "tumble",
            name: "Donna",
            label: "Tumble Wash Laundry Services",
            location: "Stafford",
            images: "1",
            cmd: "audio",
            duration: "15m 17s",
            quote: "The one thing I am good at is talking, so I do like to have a good chat with my customers .. we do NHS bed curtains too. We have our elderly regulars, they live in smaller properties where they don't have enough space for the washing machine and a tumble drier… they use the launderette as an excuse to have somebody to talk to.We’ve pulled all types of weird things out of our pipe works over the years… For my Syrian coworkers it’s more difficult for them to interact .. we’ve had a lot of Eastern European people coming into the town … You’ll see big groups of Romanians all talking together in their own language"
        },
        h312783: {
            laundrette: "northmoor",
            name: "Fiona",
            label: "Northmoor Community Launderette",
            location: "Northmoor",
            images: "1",
            cmd: "video",
            duration: "18m 43s",
            quote: "We wanted it to be right for the community that we serve… we didn’t want to put our prices up … we were an essential service for them. Kitty’s Launderette… heard about us and everything we do there … they came to visit us before they opened because it was working well."
        },
        he50051: {
            laundrette: "cleanbean_samia",
            name: "Samia",
            label: "The Clean Bean",
            location: "Bristol",
            images: "7",
            cmd: "video",
            duration: "3m 58s",
            quote: "I don’t like too much in England.. I don’t know if it’s because of the Coronavirus… I didn’t find a real friend... but it’s ok"
        },
        hab8cc0: {
            laundrette: "cleanbean_nuala",
            name: "Nuala",
            label: "The Clean Bean",
            location: "Bristol",
            images: "7",
            cmd: "video",
            duration: "8m 46s",
            quote: "It’s not glamorous but they always appreciate what we do… working men far from home, students who … need a lot of hand holding… \nYou don’t feel like you’re alone when everybody in the entire world is affected  by Covid\nWe’ve had coco put in the washing powder compartment \nIt’s a treat… for some people that’s getting their laundry done .. we make little brown parcels where we put the smalls and spray a little lavender on it"
        },
        h662483: {
            laundrette: "dizzydolly",
            name: "Jan",
            label: "Dizzy Dolly Tub",
            location: "Stourport-on-Severn",
            images: "5",
            cmd: "audio",
            duration: "18m 50s",
            quote: "I wanted a career change, I was a nurse. I don’t know why I bought a launderette… A lot of our patients.. I meant customers! are elderly … our aim is to look after the elderly, or vulnerable people. People always say ‘go to Dizzy’s, you have a lot of banter at Dizzy’s…’We’re a community that looks out for each other… they’re always popping in, \"Jan do you want a pizza, Jan, do you want some chips?\" What they don’t know about you, they make up. We call him Calvin Klein because he came in and stripped off at the top of the shop. We found a hedgehog .. I said ‘Jo, i know you love me to bits, but there’s certain things i can do… washing a hedgehog is not one of them. We found some top shelf magazines in one load of washing … i tied them up in a bag and put ‘Hi Mr, these need a real wash because they’re a bit dirty…. Sky News came down.. I had five minutes of fame. I went outside to see a man on the floor being arrested because he had a machete .. it’s not just washing clothes. It’s a local meeting place now … that’s why they call me Dizzy… I don’t mind"
        },
        h009640: {
            laundrette: "clockwash",
            name: "Matthew",
            label: "Clockwash Launderette",
            location: "King's Lynn",
            images: "5",
            cmd: "audio",
            duration: "8m 28s",
            quote: "There are people who have washing machines at home, they prefer to come in to get out of the house and bond with others. We had someone come in and want to heat his up can of soup in the tumble drier"
        },
        h95c11f: {
            laundrette: "washdry",
            name: "Duy Bui",
            label: "The Wash and Dry Shop",
            location: "St Ives",
            images: "2",
            cmd: "audio",
            duration: "5m 18s",
            quote: "I came with my mum and brother, just us three, no dad… it was difficult when I first came here I didn’t speak much English but because I was young then it was easier to adapt, but for my mum it wasn't easy so I was running this just to help out … I am from Ho Chi Minn City, or Saigon. It’s more than 85% white here, there’s only three Chinese take aways, that’s quite low I think. For a couple of years I was going to join the RAF, this year was going to be the year I joined… but Covid"
        },
        hea5b0c: {
            laundrette: "southparade",
            name: "Ed",
            label: "The South Parade Launderette",
            location: "Oxford",
            images: "4",
            cmd: "audio",
            duration: "10m 18s",
            quote: "It’s in an affluent part of Oxford - the crown and the gown. You’re virtually on call 24/7 and there could be someone need something at the shop. There was a black guy and we got chatting and I said what’s your name and he said Ted, for forty years I was a singer in the drifters and he went out with Cindy Lauper .. he said they always used to carry guns, even when they were on stage. Elton John, Lou Lou.. came in.. A guy who used to be in a band with Tony Blair…he was the singer. My partner’s a dressage rider and she has a dove tailcoat. During Covid we lost three quarters of our trade easily … we were down to  two or three customers a day and to be honest it hasn’t picked up that much, we’re still quite low."
        },
        h00ff00: {
            laundrette: "traga",
            name: "Debbie",
            label: "TRAGA Launderette",
            location: "Maidstone",
            images: "4",
            cmd: "audio",
            duration: "14m 53s",
            quote: "Some of them come in for a cup of tea and never even use the machines … we’re happy to provide tea and coffee to them and biscuits. \n She’s worked there for 40 years, I think they used to come in to see her. She ‘s taken the decision to retire because of covid, she will be missed. She showed me how to fold … her folding was impeccable. It kept her going I think, just getting up and going. It staved off the loneliness really and she made friends at the same time. They’re not coming back yet and we’re not sure whether they will. Some of them have a little sing and dance with the lady that worked here. My youngest daughter is learning the ropes"
        },
        h0000ff: {
            laundrette: "bedknobs",
            name: "Gilly",
            label: "Bedknobs BnB",
            location: "Bodmin",
            images: "2",
            cmd: "audio",
            duration: "8m 45s",
            quote: "The house found us, it was something that was meant to be"
        },
        hff00ff: {
            laundrette: "cornwallfa",
            name: "Vicky",
            label: "Cornwall Football Association",
            location: "Bodmin",
            images: "4",
            cmd: "audio",
            duration: "4m 36s",
            quote: "Our girls do leave their kit in a right mess.. they have an expectation that everything just magically comes back but that’s down to John’s hard work … John has a lot of work to do when the kits come in and they’re covered in mud and are soaking wet . It’s truly appreciated because I wouldn’t fancy taking home 40/50 shirts home to wash and dry. Sports is one of the last things that will properly return.. Right now the girls all have to take their own shirts home to wash. There’s probably 10/15% of football activity going on"
        },
        hf39200: {
            laundrette: "blackness",
            name: "Leigh",
            label: "The Blackness Launderette",
            location: "Dundee",
            images: "2",
            cmd: "audio",
            duration: "4m 4s",
            quote: "It’s quite old fashioned in here, a lot of wood going on and brick work … we’re situated beside Dundee university so we get people from all walks of life coming in here… It doesn’t feel like I’ve been here for nine years… I love my job, I just love talking to people… I am at the stage when customers come in I don't even have to ask their names .. you get service with a smile"
        },
        h00ffff: {
            laundrette: "townend",
            name: "John",
            label: "Townend Laundry Services",
            location: "Bodmin",
            images: "",
            cmd: "audio",
            duration: "12m 4s",
            quote: "You meet all sorts of characters form all walks of life … they would come in for a chat and we would put the world to rights. \nThe whole process of laundry has changed at the moment.. You have to wear so much protective equipment, everything has to be double sealed… \nWith Cornwall FA… in the winter season it can be quite a challenge when the kits come in and you start to recognise what colour it should be! \nI sometimes play a guessing game… you transport yourself back when a song plays and you think where did those years go?\n I used to work in a prison and 55% are from a black ethnic background",
        },
        hc693c2: {
            laundrette: "laura",
            name: "Laura G",
            label: "?",
            location: "?",
            images: "",
            cmd: "audio",
            duration: "12m 4s",
            quote: "In the US it’s common to have communal washing facilities… I would take it as standard to live in a house with a washing machine… \nwe would sit on these two long low benches, they felt like bus stops or waiting areas… imposing, the scale of the machines… it just was what it was",
        },
        hf3997b: {
            laundrette: "newcity",
            name: "Laura H",
            label: "The New City Laundrette",
            location: "Inverness",
            images: "",
            cmd: "txt",
            duration: "12m 4s",
            text: "When I first moved into my Highlander flat, I took Magic to a nearby laundrette on Tomnahurich St (17 Young St) and the Thai woman who owns it was pretty accepting of pugs, she once had a fat fawn one back home she said. She insisted on temporarily adopting her, she carried Magic the whole time I was there. The fellow washers were confused because this was a clean'n provision and dogs are on the whole- considered to be dirty animals. I got given dirty looks but no matter, Magic and the laundrette owner were singing to each other, her arms embraced M's paws so I could wash my duvets hands free. I know on the fb page photo the young woman on the right is her daughter, I think the woman on the left is an employee, I can only guess that she is taking the photo. She was really talkative, helpful teaching me how to use the huge washing machines and super friendly",
            quote: "When I first moved into my Highlander flat, I took Magic to a nearby laundrette on Tomnahurich St (17 Young St) and the Thai woman who owns it was pretty accepting of pugs...",
        },
    }
};